//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_system_01.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public driver()
        {
            this.orders = new HashSet<order>();
        }
    
        public int driver_id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public int cartype_id { get; set; }
        public int carproperty_id { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string adr { get; set; }
        public string shaba { get; set; }
        public string carimg { get; set; }
    
        public virtual carproperty carproperty { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual cartype cartype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
